# What do want? (Developer POV)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mongo-pvc
spec:
    storageClassName: mylocalstorage
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 20Gi

---
# How do we want it implemented? (Kubernete's cluster administrator POV)
apiVersion: v1
kind: PersistentVolume
metadata:
    name: local-storage
spec:
    storageClassName: mylocalstorage
    capacity:
        storage: 20Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        # directory location on host
        path: /mnt/some new/directory/structure/
        # this field is optional
        type: DirectoryOrCreate