apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: new-joiner
rules:
  - apiGroups: ["", "apps", "autoscaling", "extensions"] # "" is the Core API group that includes 'pods' & 'services' and "apps" is the group that includes 'deployments'.
    resources: ["*"] # pods, services, deployments...
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: put-specific-user-or-users-into-new-joiner-role
subjects:
    # List users that are going into this role
- kind: User
  name: francis-linux-login-name
roleRef:
    kind: ClusterRole
    name: new-joiner
    apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: new-joiner
    namespace: playground
rules:
- apiGroups: ["", "apps", "extensions"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: new-joiners-role-binding
    namespace: playground
subjects:
- kind: User
  name: francis-linux-login-name
roleRef:
    kind: Role
    name: new-joiner
    apiGroup: rbac.authorization.k8s.io